baseURL: https://sunghyunjun.github.io/
languageCode: ko-kr
title: Sunghyun Jun Dev Note
theme: "PaperMod"
ignoreFiles: blog-example

DefaultContentLanguage: ko
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-EFNS08FGBV

minify:
  disableXML: true
  minifyOutput: true

languages:
  ko:
    languageName: "🇰🇷 KO"
    languageCode: "ko-kr"
    weight: 1
    title: Sunghyun Jun Dev Note
    params:
      homeInfoParams:
        Title: "Hi, I'm Sunghyun Jun 👋"
        Content: Software Engineer, focused on inference optimization using PyTorch
  en:
    languageName: "🇺🇸 EN"
    languageCode: "en-us"
    weight: 2
    title: Sunghyun Jun Dev Note (EN)
    params:
      homeInfoParams:
        Title: "Hi, I'm Sunghyun Jun 👋"
        Content: Software Engineer, focused on inference optimization using PyTorch

taxonomies:
  category: categories
  tag: tags

params:
  env: production
  title: Sunghyun Jun Dev Note
  description: "Sunghyun Jun Dev Note"
  keywords: [Blog, Portfolio, PaperMod]
  author: Sunghyun Jun
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  socialIcons:
    - name: email
      url: "mailto:sunghyunjun1224@gmail.com"
    - name: linkedin
      url: "https://www.linkedin.com/in/전성현-sunghyun-jun-0a2156278"
    - name: github
      url: "https://github.com/sunghyunjun"
    - name: kaggle
      url: "https://www.kaggle.com/sunghyunjun"

  analytics:
    google:
      SiteVerificationTag: "DIWwwU8ckTOPhkZdU_PgbNYw984L1km4b9KMFF6mD5A"
    naver:
      SiteVerificationTag: "7a0f56cfc3f5f2d152ff08dd9238b3dcabe5dbfc"

  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20

pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
